# specs/hardening/design.md's AWS Deploy IaC section (Req 17-18). Every
# secret-shaped value here is either generated by Terraform into Secrets
# Manager (db/jwt) or left null with the real value entered out-of-band
# post-apply (see secrets.tf and README.md) — never a plaintext default.

variable "aws_region" {
  description = "AWS region for all resources."
  type        = string
  default     = "eu-west-1" # no AWS footprint in Tanzania/EA; closest region with full service coverage. Revisit against real latency measurements before a real cutover.
}

variable "project_name" {
  description = "Short name prefixed onto every resource (RDS identifier, ECR repo, ECS cluster, etc.)."
  type        = string
  default     = "groceries-app"
}

variable "environment" {
  description = "Deployment environment name (staging|production), suffixed onto resource names/tags."
  type        = string
  default     = "staging"
}

variable "vpc_cidr" {
  description = "CIDR block for the VPC."
  type        = string
  default     = "10.20.0.0/16"
}

variable "availability_zones" {
  description = "Two AZs to spread public/private subnets across (constitution.md doesn't mandate multi-AZ; two is the minimum for an ALB + RDS Multi-AZ-capable layout)."
  type        = list(string)
  default     = ["eu-west-1a", "eu-west-1b"]
}

variable "db_name" {
  description = "Postgres database name — matches backend/.env's DB_NAME so no application config changes on cutover."
  type        = string
  default     = "groceries"
}

variable "db_username" {
  description = "Postgres master username."
  type        = string
  default     = "groceries"
}

variable "db_instance_class" {
  description = "RDS instance class. db.t4g.micro is the free-tier-eligible floor — size up before real production traffic per the load-test results in work.md."
  type        = string
  default     = "db.t4g.micro"
}

variable "redis_node_type" {
  description = "ElastiCache node type."
  type        = string
  default     = "cache.t4g.micro"
}

variable "container_image" {
  description = "Full ECR image URI:tag to deploy (e.g. \"<account>.dkr.ecr.<region>.amazonaws.com/groceries-app-backend:<sha>\"). Left without a default — CI/CD supplies this per-deploy; there is no meaningful default before the ECR repo (ecr.tf) has ever had an image pushed to it."
  type        = string
}

variable "container_port" {
  description = "Port the backend container listens on — matches backend/.env's PORT."
  type        = number
  default     = 4000
}

variable "task_cpu" {
  description = "Fargate task CPU units (256 = 0.25 vCPU)."
  type        = number
  default     = 256
}

variable "task_memory" {
  description = "Fargate task memory (MiB)."
  type        = number
  default     = 512
}

variable "desired_count" {
  description = "Number of Fargate tasks to run. >1 recommended once real traffic exists — the realtime WebSocket gateway (specs/realtime/design.md) doesn't require sticky sessions since admin-web's client falls back to polling per-connection, not per-task."
  type        = number
  default     = 1
}

variable "acm_certificate_arn" {
  description = "ACM certificate ARN for the ALB's HTTPS listener. Provisioning a real cert needs a real domain — out of scope for this pass (specs/hardening/requirements.md's Scoping decision). Left null so `terraform plan` still works; `apply` will fail on the HTTPS listener until this is supplied, which is intentional — better than silently deploying HTTP-only for a callback URL that will carry MNO webhook payloads."
  type        = string
  default     = null
}

variable "admin_web_origin" {
  description = "Browser origin allowed by the realtime WebSocket gateway's CORS check (ADMIN_WEB_ORIGIN, see src/realtime/orders.gateway.ts). Wherever admin-web itself ends up hosted — out of scope here, see design.md's AWS Deploy IaC note that only the backend's target architecture is covered."
  type        = string
  default     = null
}

variable "jwt_access_token_ttl_seconds" {
  description = "Mirrors backend's JWT_ACCESS_TOKEN_TTL — see specs/hardening/design.md's JWT TTL section (ISSUE-009) for why this stays at 24h."
  type        = number
  default     = 86400
}
